### ISSUE TITLE
Some samples still broken

### ISSUE THREAD

**Issue by OmegaFoxie** [Yukitty/in_org#4]
Aside from the previously mentioned Wave 63 sample (Cave Story, Living Waterway, was gonna make a list of other songs that use this sample but the forgot about it), which is still broken (I'm talking about that slight buzzing, which may have gotten even worse with 1.09, there's also the songs that use very low pitched samples (Pulse, Gestation) sound weird. I can't really say if it's the sample itself, it might be an interpolation issue or something, I'm no expert sadly. And also not all Org Maker 2.10 samples are supported, only some of them (which I find a bit weird). I honestly hate to be bothering you with this, it's just I really want to see an accurate org playback plugin for windows based media players (and in this case, winamp).

**Comment by Yukitty** [comment]
I don't have enough data to do any better than this. I only used what was given to me. If it's missing, I don't have it. Org Maker _2.10_ probably didn't even exist at the time. The low pitched samples are drums, which are handled completely differently from the main instruments, so that's a different issue entirely.
